apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyboard-generator
  namespace: legacy
  labels:
    app: keyboard-generator
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      app: keyboard-generator
  template:
    metadata:
      labels:
        app: keyboard-generator
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: keyboard-generator
          image: tonypai/keyboard-generator
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: keyboard-generator
  namespace: legacy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: keyboard-generator
