apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary-gpt-bot
  namespace: legacy
  labels:
    app: summary-gpt-bot
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      app: summary-gpt-bot
  template:
    metadata:
      labels:
        app: summary-gpt-bot
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: summary-gpt-bot
          image: tonypai/summary-gpt-bot
          env:
            - name: OPENAI_API_KEY
              value: "${OPENAI_API_KEY}"
            - name: OPENAI_MODEL
              value: "gpt-3.5-turbo"
            - name: TELEGRAM_TOKEN
              value: "${TELEGRAM_TOKEN}"
            - name: TS_LANG
              value: "Traditional Chinese"
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 256Mi
