version: '3'

services:
  prom:
    image: prom/prometheus:v2.39.0
    container_name: prometheus
    volumes:
      - ./prom-data:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  gf:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./gf-data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
