version: '3'

services:
  prom:
    image: prom/prometheus:v2.39.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  gf:
    image: grafana/grafana
    ports:
      - "3000:3000"
