apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: https-secret
  namespace: cert-manager
spec:
  secretName: https-secret
  issuerRef: 
    kind: ClusterIssuer
    name: cloudflare
  commonName: "${WILDCARD_CN}"
  dnsNames:
    - "${WILDCARD_CN}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "legacy"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "legacy"
